'use strict';

/**
 * Format scan results into a CLAUDE.md file.
 */
function formatClaude(scanResult, options = {}) {
  const { projectName, stack, structure, conventions } = scanResult;
  const lines = [];

  const h1 = (t) => lines.push(`# ${t}\n`);
  const h2 = (t) => lines.push(`\n## ${t}\n`);
  const li = (t) => lines.push(`- ${t}`);
  const p = (t) => lines.push(t);
  const blank = () => lines.push('');
  const code = (lang, content) => {
    lines.push('```' + lang);
    lines.push(content);
    lines.push('```');
  };

  // Header
  h1(`CLAUDE.md — ${projectName}`);
  p('> Auto-generated by [rulegen](https://github.com/vexorkai/rulegen). Review and customize.');
  blank();

  // Tech Stack
  h2('Tech Stack');
  if (stack.runtime) li(`Runtime: **${stack.runtime}**`);
  if (stack.packageManager) li(`Package manager: **${stack.packageManager}**`);
  if (stack.languages.length > 0) li(`Languages: ${stack.languages.join(', ')}`);
  if (stack.frameworks.length > 0) li(`Frameworks/Libraries: ${stack.frameworks.join(', ')}`);
  if (stack.tools.length > 0) li(`Tools: ${stack.tools.join(', ')}`);

  // Commands
  const scripts = stack.scripts || {};
  const importantScripts = ['dev', 'start', 'build', 'test', 'lint', 'format', 'typecheck', 'check', 'clean'];
  const filteredScripts = importantScripts.filter(s => scripts[s]);
  if (filteredScripts.length > 0) {
    h2('Common Commands');
    const pm = stack.packageManager || 'npm';
    const run = pm === 'npm' ? 'npm run' : pm === 'yarn' ? 'yarn' : pm;
    for (const s of filteredScripts) {
      li(`\`${run} ${s}\` — ${scripts[s]}`);
    }
    // Also check for Makefile, etc.
  }

  // Project Structure
  h2('Project Structure');
  blank();
  code('', structure.tree);
  blank();

  if (structure.notes.length > 0) {
    for (const note of structure.notes) li(note);
    blank();
  }

  // Key Files
  if (structure.keyFiles.length > 0) {
    h2('Key Files');
    for (const kf of structure.keyFiles) {
      li(`\`${kf.path}\` — ${kf.label}`);
    }
  }

  // Conventions
  h2('Conventions');
  if (conventions.naming) li(`File naming: ${conventions.naming}`);
  if (conventions.testStyle) li(`Tests: ${conventions.testStyle}`);
  if (conventions.importStyle) li(`Imports: ${conventions.importStyle}`);
  if (conventions.codeStyle && conventions.codeStyle.length > 0) {
    for (const note of conventions.codeStyle) li(note);
  }

  // What to Avoid
  if (conventions.avoidList && conventions.avoidList.length > 0) {
    h2('What to Avoid');
    for (const item of conventions.avoidList) li(item);
  }

  // Notes section for user to fill in
  h2('Notes');
  p('<!-- Add project-specific notes here: architecture decisions, gotchas, links to docs -->');

  return lines.join('\n') + '\n';
}

module.exports = { formatClaude };
