'use strict';

/**
 * Format scan results into .cursorrules (plain text, terse instructions).
 * Cursor rules work best as direct, imperative instructions to the AI.
 */
function formatCursor(scanResult) {
  const { projectName, stack, structure, conventions } = scanResult;
  const lines = [];

  const p = (t) => lines.push(t);
  const blank = () => lines.push('');

  p(`# ${projectName} — Cursor Rules`);
  p(`# Auto-generated by rulegen (https://github.com/vexorkai/rulegen). Review and customize.`);
  blank();

  // Stack context
  const stackParts = [];
  if (stack.runtime) stackParts.push(stack.runtime);
  if (stack.languages.length) stackParts.push(stack.languages.join('/'));
  if (stack.frameworks.length) stackParts.push(stack.frameworks.slice(0, 4).join(', '));
  if (stackParts.length) {
    p(`This is a ${stackParts.join(', ')} project.`);
    blank();
  }

  // Package manager
  if (stack.packageManager) {
    p(`Use ${stack.packageManager} for all package management. Do not use npm if pnpm/yarn/bun is the package manager.`);
    blank();
  }

  // Import style
  if (conventions.importStyle) {
    p(`Imports: ${conventions.importStyle}.`);
  }

  // Naming
  if (conventions.naming && !conventions.naming.includes('Unable')) {
    p(`File naming convention: ${conventions.naming}.`);
  }

  // TypeScript
  if (stack.frameworks.includes('TypeScript') || stack.languages.includes('TypeScript')) {
    const tsStrict = (conventions.codeStyle || []).some(s => s.includes('strict'));
    if (tsStrict) p(`TypeScript strict mode is enabled. Do not use 'any'. Add proper types.`);
    else p(`Use TypeScript with proper typing. Avoid 'any'.`);
  }

  blank();

  // Test style
  if (conventions.testStyle && !conventions.testStyle.includes('No test')) {
    p(`Tests: ${conventions.testStyle}.`);
    p(`When adding new features, include tests following the existing pattern.`);
    blank();
  }

  // Scripts
  const scripts = stack.scripts || {};
  if (scripts.test) p(`Run tests: ${stack.packageManager || 'npm'} run test`);
  if (scripts.lint) p(`Run lint: ${stack.packageManager || 'npm'} run lint`);
  if (scripts.build) p(`Build: ${stack.packageManager || 'npm'} run build`);
  blank();

  // Avoids
  if (conventions.avoidList && conventions.avoidList.length > 0) {
    p('Avoid:');
    for (const item of conventions.avoidList) {
      p(`- ${item}`);
    }
    blank();
  }

  // Placeholder
  p('# Add project-specific rules below:');
  p('# - Architecture patterns');
  p('# - API conventions');
  p('# - Domain-specific rules');

  return lines.join('\n') + '\n';
}

module.exports = { formatCursor };
